In [2]:
import numpy as np


In [3]:
#scenerio 1

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [5]:
#Scenerio 2

a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [6]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

#   Rules for Broadcasting

In [7]:
# if x = m  and y = n, operation will take place

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [8]:
# if x = 1  and y = n, operation will take place(Same dimension)

a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)
print(a5,a6)

[[0 1 2]] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# if x = 1  and y! = n,  then operation will not take place

a9 = np.arange(3).reshape(1,3)
a10 = np.arange(16).reshape(4,4)
print(a9)
print(a10)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [10]:
a9 + a10

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [12]:
# if x = 1  and n = 1 then y == m,  then operation will  take place

a11 = np.arange(3).reshape(1,3)
a12 = np.arange(3).reshape(3,1)
print(a11)
print(a12)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [13]:
a11 + a12

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [15]:
# if x = 1  and y = 1,  then operation will  take place np matter what

a13 = np.arange(1).reshape(1,1)
a14 = np.arange(20).reshape(4,5)
print(a13)
print(a14)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
a13 + a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
# if they are of differnt dimensions

a15 = np.arange(4)
a16 = np.arange(20).reshape(5,4)

print(a15)
print(a16)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [19]:
a15 + a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

# Some Inportant numpy Functions

In [27]:
import numpy as np
np.random.random()

0.14675589081711304

In [23]:
# If we use seed we get same random value on running again and again.
np.random.seed(1)
np.random.random()

0.417022004702574

In [33]:
np.random.uniform(3,10)

5.934361600823063

In [34]:
np.random.uniform(1,100,10)

array([68.83673054, 21.24077272, 87.9336262 ,  3.71137173, 67.37628351,
       42.31317543, 56.31029302, 14.89830692, 20.61204742, 80.2737123 ])

In [35]:
np.random.uniform(1,100,10).reshape(2,5)

array([[96.857896  , 32.02899364, 69.53993895, 87.76252608, 89.56605969],
       [ 9.41937693,  4.86642354, 17.81321154, 87.93610784, 10.73633655]])

In [37]:
np.random.randint(1,20,2)

array([ 7, 18])

In [40]:
np.random.randint(1,10,15).reshape(3,5)

array([[5, 1, 4, 3, 1],
       [5, 3, 8, 8, 9],
       [7, 4, 8, 8, 5]])

In [42]:
a = np.random.randint(1,10,6)
a

array([6, 4, 7, 9, 1, 3])

In [43]:
np.max(a)

9

In [44]:
np.min(a)

1

In [46]:
np.argmax(a)

3

In [47]:
a[np.argmax(a)]

9

In [48]:
a[np.argmin(a)]

1

In [49]:
a = np.random.randint(1,10,6)
a

array([8, 8, 8, 4, 1, 9])

In [50]:
a[a%2==1]=-1
a

array([ 8,  8,  8,  4, -1, -1])

In [56]:
a = np.random.randint(1,50,6)
a

array([31, 42, 25, 19, 34,  3])

In [57]:
np.where(a%2==1,-1,a)

array([-1, 42, -1, -1, 34, -1])

In [58]:
a

array([31, 42, 25, 19, 34,  3])

In [59]:
a = np.random.randint(1,50,10)
a

array([45, 29, 40, 35, 11, 33, 42, 19, 23,  7])

In [61]:
b = np.sort(a)
b

array([ 7, 11, 19, 23, 29, 33, 35, 40, 42, 45])

In [62]:
np.percentile(a,25)


20.0

In [63]:
np.percentile(a,50)

31.0

In [64]:
np.percentile(a,99.8)

44.946